### ISSUE TITLE
PepeLand

### ISSUE THREAD

**Issue by TWRS1** [Disguys/Valmata#5]
### Server name and IP

play.pepeland.net

### Server icon

![7571C6B4-DD1B-4F07-BD58-10596C3669A0](https://user-images.githubusercontent.com/81922259/140329175-bb6d7c36-af81-4326-8d1d-774857c4400b.png)

### Agreements

- [X] I made sure that this server icon is missing
- [X] I made icon is size 512x512 and .png format

**Comment by Disguys** [comment]
Привет, значок сервера PepeLand уже присутствует в моде CraftPresence. 
Я добавил его еще тогда, когда была выпущена версия RC-1, но с момента выпуска этой версии прошло уже более 3-ех месяцев. Проблема вся в том, что я добавлял его на айпи `play.pepeland.club` еще давно. С тех пор у данного сервера изменился айпи на `play.pepeland.net`.

У меня есть для тебя возможные варианты решения:
1. Я изменю айпи данного сервера с поддержкой его значка в следующей версии модпака 1.1, но она будет выпущена в течении 2-3 недель.

2. Вы можете изменить значок для данного сервера в ручную, для этого следуйте моей инстуркции ниже:
1 - В главном меню найдите кнопку для показа списка модов -> выберите мод `CraftPresence` -> откройте его 
настройки
2 - Нажмите на кнопку `Customize Server Messages` -> `Server Messages` , затем выберите сервер с айпи `play.pepeland.net` -> `Continue`
3 - Нажмите `Change Icon` -> выберите иконку PepeLand, также можете изменить название сервера в строке `Message:`
4 - Нажмите  `Continue` -> `Back` -> `Save`.

Если возникнет проблема, то также не стесняйтесь открывать тему. Наслаждайтесь =) 
![image](https://user-images.githubusercontent.com/60795989/140345432-71a00647-f645-48f6-841b-5fd496b518cd.png)

**Comment by TWRS1** [comment]
Вас понял. Лучше подходит вариант с изменением (обновлением, если точнее) адреса сервера. Спасибо!

**Comment by Disguys** [comment]
@TWRS1 Исправлено в версии 1.1, приятной игры! :3

https://github.com/Disguys/Valmata/releases
https://www.curseforge.com/minecraft/modpacks/valmata
